### ISSUE TITLE
Feature request: archive download

### ISSUE THREAD

**Issue by F1LT3R** [oorabona/tumblrip#2]
Hey nice work! I love this ripper.

It would be awesome to make it work for archives too, Eg: http://blogname.tumblr.com/archive, as sometimes this contains better content.

**Comment by oorabona** [comment]
Thank you very much ! It's great to know that this software is useful for others :+1: 

Aren't all archives blog posts (old of course) ? When doing a fresh rip, it downloads all posts it can find: I hope **every** post is present in API response !

If not, do you have an example of a post that exists in the archives and not downloaded ?
I cannot imagine the archives totally absent from API returned results, but if you know a way to get hands on them, I'd happily implement these additionnal API calls.

Yeah, I would rather prefer sticking with plain and clean API calls (and Tumblr API is cool) than crawling/parsing HTML (`wget` does that better than me) !

Thanks for your feedback!

**Comment by F1LT3R** [comment]
You might be right actually. I will give this a try next time I use it.

Thanks
