### ISSUE TITLE
Question: Limit to amount downloaded.

### ISSUE THREAD

**Issue by PixelTom** [oorabona/tumblrip#3]
Hi, more of a question than an issue.

I was trying this downloader out with a Tumblr I frequent, and so far it's up to 18750 images.

Is there any way to limit the amount downloaded or does it only go through the entire account in one big hit?

**Comment by oorabona** [comment]
Hello @PixelTom ,

This tool has been designed around the idea of backuping. So yes the entire account in one big hit.
Still, you can stop it anytime if limit (bandwidth, etc.) is an issue.
The fact that it maintains its own database makes this scenario perfect for incremental backup.

I just tried to implement the "limit" option, but then the question arise : should limit apply to cache update ? If so, there can be cache inconsistencies and that is not tolerable. So limits will only apply to how many images are downloaded.

If that fits your requirements, you can download the newly pushed version 😄
